# Generated by Django 4.2.6 on 2023-12-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(choices=[('Lahore', 'Lahore'), ('Sahiwal', 'Sahiwal'), ('Okara', 'Okara')], max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LandOwner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('area', models.IntegerField()),
                ('ownerid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='members.landowner')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=' ', max_length=10)),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.admin')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.landowner')),
            ],
        ),
        migrations.CreateModel(
            name='LandValuation',
            fields=[
                ('valuation_id', models.AutoField(primary_key=True, serialize=False)),
                ('valuation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valuation_date', models.DateField()),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.landplot')),
            ],
        ),
        migrations.CreateModel(
            name='LandTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Sale', 'SALE'), ('Lease', 'LEASE'), ('Transfer', 'TRANSFER')], default=' ', max_length=50)),
                ('transaction_date', models.DateField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.landplot')),
            ],
        ),
        migrations.CreateModel(
            name='LandTenure',
            fields=[
                ('tenure_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenure_type', models.CharField(choices=[('Freehold', 'FREEHOLD'), ('Leasehold', 'LEASEHOLD'), ('Other', 'OTHER')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.landplot')),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('infrastructure_id', models.AutoField(primary_key=True, serialize=False)),
                ('infrastructure_type', models.CharField(choices=[('Road', 'ROAD'), ('Bridge', 'BRIDGE'), ('Building', 'BUILDING'), ('Other', 'OTHER')], max_length=50)),
                ('infrastructure_name', models.CharField(max_length=100)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.landplot')),
            ],
        ),
    ]
