# Generated by Django 4.2.6 on 2023-12-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='landowner',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
