# Generated by Django 5.0 on 2023-12-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_landowner_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='infrastructure_type',
            field=models.CharField(choices=[('ROAD', 'Road'), ('BRIDGE', 'Bridge'), ('BUILDING', 'Building'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='landtenure',
            name='tenure_type',
            field=models.CharField(choices=[('FREEHOLD', 'Freehold'), ('LEASEHOLD', 'Leasehold'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='landtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('LEASE', 'Lease'), ('TRANSFER', 'Transfer')], max_length=20),
        ),
    ]
